name: Initialize Liquibase
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install jq tool
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.27.0/liquibase-4.27.0.tar.gz
          tar -xvzf liquibase-4.27.0.tar.gz
          export PATH=$PATH:/liquibase/
          sudo chmod +x /liquibase/liquibase.sh
          source /liquibase/liquibase.sh
          
